## changed at Wed Aug 05 11:36:42 MSK 2026
#Wed Aug 05 11:36:42 MSK 2026
com.gigaide.database.elements.view.SqlFileFrameElement.shouldUse=true
com.gigaide.database.elements.view.SqlFileFrameExplorerElement.shouldUse=true
com.gigaide.database.elements.view.SqlStatementExplorerElement.shouldUse=true
com.gigaide.database.ui.treeview.DataSourcesViewNode.shouldUse=true
com.gigaide.elements.ext.marker.framework.EndPointPyFunctionMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.ForeignKeyMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.ManyToManyMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.OneToOneMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.PyApplicationRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.PyCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.PyDecoratorRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.PyImplInheritRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.TableMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.java.JavaAnnotationRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.java.JavaCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.JsCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.JsImplInheritRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.angular.ControllerMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.angular.DirectiveMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.angular.FactoryMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.angular.ModuleMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.angular.ServiceMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.ComponentsMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.ComputedMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.DataMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.LifeCycleMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.MethodsMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.js.vue.WatchMarker.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtAnnotationRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtCallRoled.shouldMark=true
com.gigaide.elements.ext.marker.framework.kt.KtImplInheritRoled.shouldMark=true
com.gigaide.elements.ext.marker.solution.UATJsSolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.UATPySolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.java.JavaClassSolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.java.JavaVariableBeanUsage.shouldMark=true
com.gigaide.elements.ext.marker.solution.kt.KtClassSolution.shouldMark=true
com.gigaide.elements.ext.marker.solution.kt.KtVariableBeanUsage.shouldMark=true
com.gigaide.elements.ext.marker.tms.TmsLinkMethod.shouldMark=true
com.gigaide.elements.ext.menu.TmsToExplorerMarkerAction.shouldAct=true
com.gigaide.elements.ext.menu.ToFrameworkAction.shouldAct=true
com.gigaide.elements.ext.view.DefaultFrameElement.shouldUse=true
com.gigaide.elements.ext.view.DefaultFrameMarker.shouldUse=true
com.gigaide.elements.ext.view.DefaultFramework.shouldUse=true
com.gigaide.elements.ext.view.DefaultJavaxPA.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolution.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolutionElement.shouldUse=true
com.gigaide.elements.ext.view.DefaultSolutionMarker.shouldUse=true
com.gigaide.elements.ext.view.ExplorerFrameElement.shouldUse=true
com.gigaide.elements.ext.view.ExplorerFrameMarker.shouldUse=true
com.gigaide.elements.ext.view.ExplorerSolutionElement.shouldUse=true
com.gigaide.elements.ext.view.ExplorerSolutionMarker.shouldUse=true
com.gigaide.elements.ext.view.bean.DefaultEJB.shouldUse=true
com.gigaide.elements.ext.view.bean.DefaultSpringAutowired.shouldUse=true
com.gigaide.elements.ext.view.bean.ExplorerEJBBean.shouldUse=true
com.gigaide.elements.ext.view.bean.ExplorerSpringBean.shouldUse=true
com.gigaide.elements.ext.view.bridge.DefaultJavaSpringRepository.shouldUse=true
com.gigaide.elements.ext.view.bridge.ExplorerSpringRepository.shouldUse=true
com.gigaide.elements.ext.view.data.DefaultJakartaPA.shouldUse=true
com.gigaide.elements.ext.view.data.ExplorerJavaxPA.shouldUse=true
com.gigaide.elements.ext.view.data.python.PythonDBColumnExplorer.shouldUse=true
com.gigaide.elements.ext.view.data.python.PythonExplorerPA.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJakartaRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJakartaWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJavaBlade.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJavaSpringController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJavaSpringEndpoint.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJaxRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultJaxWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.DefaultPythonEndPointController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerBlade.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerJaxRs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerJaxWs.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerPythonController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerSpringController.shouldUse=true
com.gigaide.elements.ext.view.endpoint.ExplorerSpringEndpoint.shouldUse=true
com.gigaide.elements.ext.view.factory.DefaultJavaSpringConfiguration.shouldUse=true
com.gigaide.elements.ext.view.factory.ExplorerSpringFactory.shouldUse=true
com.gigaide.elements.ext.view.integration.DefaultJavaSpringIntegration.shouldUse=true
com.gigaide.elements.ext.view.integration.ExplorerSpringIntegration.shouldUse=true
com.gigaide.elements.ext.view.js.ControllerExplorer.shouldUse=true
com.gigaide.elements.ext.view.js.JsControllerActionExplorer.shouldUse=true
com.gigaide.elements.ext.view.js.view.SmartClientViewAttributeExplorer.shouldUse=true
com.gigaide.elements.ext.view.js.view.SmartClientViewExplorer.shouldUse=true
com.gigaide.elements.ext.view.security.DefaultJavaJakartaSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.DefaultJavaJavaxSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.DefaultJavaSpringSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.ExplorerJakartaSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.ExplorerJavaxSecurity.shouldUse=true
com.gigaide.elements.ext.view.security.ExplorerSpringSecurity.shouldUse=true
com.gigaide.elements.ext.view.testing.DefaultJavaAllureTesting.shouldUse=true
com.gigaide.elements.ext.view.testing.ExplorerAllureTesting.shouldUse=true
com.gigaide.elements.service.marker.config.MarkerConfigHolder.analyzePriority=false
com.gigaide.elements.service.marker.config.MarkerConfigHolder.autoAnalize=false
com.gigaide.endpoint.marker.environment.EnvironmentMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.EndpointMethodMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.InteractionHttpMethodMarker.shouldMark=true
com.gigaide.endpoint.marker.interaction.InteractionUrlMarker.shouldMark=true
com.gigaide.endpoint.menu.environment.SelectEnvironmentAction.shouldAct=true
com.gigaide.endpoint.menu.interection.EndpointToExplorerAction.shouldAct=true
com.gigaide.endpoint.menu.interection.InteractionRunAction.shouldAct=true
com.gigaide.endpoint.menu.interection.InteractionToExplorerAction.shouldAct=true
com.gigaide.endpoint.menu.interection.PythonEndpointToExplorerAction.shouldAct=true
com.gigaide.endpoint.view.environment.EnvironmentSolutionElement.shouldUse=true
com.gigaide.endpoint.view.interaction.HttpMethodExplorerElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionExplorerFrameElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionExplorerSolutionElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionFileFrameElement.shouldUse=true
com.gigaide.endpoint.view.interaction.InteractionFileSolutionElement.shouldUse=true
com.intellij.spring.elements.marker.NavigateToAutowiredCandidatesLineMarkerProvider.NavigateToAutowiredCandidatesLineMarkerElement.shouldMark=true
